_target_: navsim.planning.utils.multithreading.worker_ray_no_torch.RayDistributedNoTorch
_convert_: 'all'
master_node_ip: null      # 连接本地Ray集群
threads_per_node: null    # 不指定CPU数量，使用现有集群资源
debug_mode: false
log_to_driver: true
logs_subdir: 'logs'
use_distributed: false    # 使用本地Ray集群