hydra:
  run:
    dir: ${output_dir}
  output_subdir: ${output_dir}/code/hydra           # Store hydra's config breakdown here for debugging
  searchpath:                                       # Only <exp_dir> in these paths are discoverable
    - pkg://navsim.planning.script.config.common 
  job:
    chdir: False

defaults:
  - default_common
  - default_evaluation
  - default_scoring_parameters
  - agent: diffusiondrive_style_agent
  - worker: sequential
  - _self_
  - override train_test_split: navtest

metric_cache_path: ${oc.env:NAVSIM_EXP_ROOT}/metric_cache # path to metric cache

# Enable visualization output
enable_visualization: true

# Visualization specific settings
visualization_output_dir: "pdm_evaluation_visualizations"
max_visualizations: 50

# Override experiment name to include visualization
experiment_name: "eval_with_visualization"

# Force single-threaded execution for visualization compatibility